modules:
  command:
    bypass: "cyclone.bypass.command"
    punish: "ban %player% Violating filter"
    enabled: true
    commands:
      - "(?:mv)(?:h)(?:elp)?"
      - "(?:mv)(?:s)(?:earch)?"
  message:
    bypass: "cyclone.bypass.message"
    punish: "kick %player% Violating filter"
    enabled: false
    messages:
      - "\\$\\{.+\\}" # log4j