name: Cyclone
version: ${pluginVersion}
main: net.deltapvp.cyclone.Cyclone
description: Cyclone plugin
api-version: 1.13
website: https://github.com/powercasgamer/Cyclone
author: powercas_gamer
commands:
  cyclone: